spring:
  cloud:
    nacos:
      discovery:
        server-addr: 106.54.70.153:8848
    gateway:
      routes:
        - id: test-route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq-route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: third_party_router
          uri: lb://gulimall-thrid-party
          ## 路径匹配断言
          predicates:
            - Path=/api/thirdparty/**
          ## 路径重写
          filters:
            - RewritePath=/api/thirdparty(?<segment>/?.*),/$\{segment}
        - id: product_router
          ##lb: 代表 load balance 负载均衡
          uri: lb://gulimall-product
          ## 路径匹配断言
          predicates:
            - Path=/api/product/**
          ## 路径重写
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
        ##模糊路由匹配后置xx
        - id: admin_router
          ##lb: 代表 load balance 负载均衡
          uri: lb://renren-fast
          ## 路径匹配断言
          predicates:
            - Path=/api/**
          ## 路径重写
          filters:
            - RewritePath=/api/(?<segment>/?.*),/renren-fast/$\{segment}
server:
  port: 88
## 前端项目，/api
## http://localhost:88/api//captcha.jpg http://localhost:8080/renren-fast/captcha.jpg